config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/recommender-system:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/recommender-system.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-rust-elephant.sh
        container: qc.acc_pokey-olive-catfish
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-indigo-dalmatian.sh
        container: qc.doc_slimy-lilac-chamois
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-heliotrope-mole.sh
        container: qc.doc_chewy-yellow-chipmunk
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-linen-terrier.sh
        container: qc.doc_scummy-cornflower-dogfish
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-coral-ibis.sh
        container: qc.lic_goopy-vermilion-hyrax
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-crimson-jaguar.sh
        container: qc.ver_sleazy-amethyst-pinscher
timeout: 5400
