config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/recommender-system:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/recommender-system.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-indigo-quokka.sh
        container: qc.acc_wheezy-wheat-baboon
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-tan-beagle.sh
        container: qc.doc_scaly-corn-yak
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-scarlet-dachsbracke.sh
        container: qc.doc_whiny-orchid-mist
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cobalt-neanderthal.sh
        container: qc.doc_paltry-peach-tiger
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cyan-tzu.sh
        container: qc.lic_smelly-puce-akita
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/recommender-system get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cyan-wombat.sh
        container: qc.ver_woolly-seashell-turtle
timeout: 5400
